# Site settings
baseurl = "https://shellfly.org/"
languageCode = "zh-cn"
defaultContentLanguage="zh-cn"
title = "shellfly's blog"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-28584868-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "shellfly"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -10

  [[menu.main]]
    identifier = "en"
    name = "En"
    pre = "<i class='fa fa-heart'></i>"
    url = "/en/"
    weight = -100


[languages]
  [languages.en]
	languageCode = "en-us"
    contentDir = "content/en"
    languageName = "English"
    weight = 2
  [languages.zh-cn]
	languageCode = "zh-cn"
    contentDir = "content/zh-cn"
    languageName = "Chinese"
    weight = 1

[params]
	name = "shellfly"
	description = "shellfly's blog about something he likes"
	bio = "翼をください"
	# Enter optionally your twitter account
	twitter = "shell0fly"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = '若无特别声明，本网站作品采用<a rel="license" class="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
	# Sharing options and author information in posts
	aboutAuthor = "翼をください"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/shell0fly"
    github   = "https://www.github.com/shellfly"
